; ==============================================================================
; Eventing

; how can we pipe an event to a specific node only?
; There is no point in making this arbitrary right now?

; Tell you that an event exists
MESSAGE_EVENT_INFORM = (
    MESSAGE_EVENT_ID,
    EVENT_MAP
)

; You are emitting an event
MESSAGE_EVENT_INVOKE = (
    MESSAGE_EVENT_INVOKE_ID,
    EVENT_ID: int, ; the event you are invoking
    CONTENT: map, ; the content of the event
)

EVENT_MAP = {
    EVENT_ID: EVENT_DEFINITION,
    ;...
}

EVENT_DEFINITION = {
    NAME: text,
    ; expected content?
}