; An arbitrary identifier for a large asset
LARGE_ASSET_ID = i64

; A request for a large asset.
LARGE_ASSET_REQUEST = (
    ; Request identifier. This should be a unique identifier;
    ; no two requests should have the same identifier at a time. After request and response, the identifier can be re-used.
    UUID
    
    ; The identifier of the asset to obtain
    LARGE_ASSET_ID
)

; A request response. 
LARGE_ASSET_REPLY = (
    ; The request identifier
    UUID

    ; Metadata about the asset
    LARGE_ASSET_META,

    ; Either the content requested, or an error
    RESULT<BYTE_STRING, LARGE_ASSET_ERROR>
)

LARGE_ASSET_ERROR = (
    ; Error message
    LARGE_STRING
)