

MESSAGE_TRANSACTION_ID = 1
MESSAGE_TRANSACTION_REPLY_ID = -1

MESSAGE_PROBE_ID = 2
MESSAGE_PROBE_REPLY_ID = -2

MESSAGE_INTRO_ID = 3
MESSAGE_INTRO_REPLY_ID = -3

MESSAGE_RPC_ID = 4

MESSAGE_RPC_INVOKE_ID = 5
MESSAGE_RPC_INVOKE_REPLY_ID = -5

MESSAGE_RPC_INVOKE_BATCH_ID = 6
MESSAGE_RPC_INVOKE_BATCH_REPLY_ID = -6