CONTENT_MESSAGE = 
    MESSAGE_CREATE_ENTITY /
    MESSAGE_DELETE_ENTITY /
    MESSAGE_COMPONENT /
    MESSAGE_RESOUCE /
    MESSAGE_ASSET

; TODO are the integer sizes here appropriate?

; An identifier for a component type
; Note: This is a signed integer! See below for rationale
COMPONENT_ID = i16

; An identifier for a resource type
RESOURCE_ID = i16

; An identifier for a specific asset. Different asset types are considered different namespaces for these IDs
ASSET_ID = u32

; A specific asset type
ASSET_TYPE_ID = u16

; These are all u8!
MESSAGE_CREATE_ENTITY_ID = 0
MESSAGE_CREATE_ENTITY_BATCH_ID = 1
MESSAGE_DELETE_ENTITY_ID = 2
MESSAGE_DELETE_ENTITY_BATCH_ID = 3
MESSAGE_COMPONENT_ID = 4
MESSAGE_RESOURCE_ID = 5
MESSAGE_ASSET_ID = 6

; ==============================================================================
; Entity message
; A demand to create an entity or list of entities. 
MESSAGE_CREATE_ENTITY = (
    MESSAGE_CREATE_ENTITY_ID,
    ENTITY_ID
)

MESSAGE_CREATE_ENTITY_BATCH = (
    MESSAGE_CREATE_ENTITY_BATCH_ID,
    ARRAY<u32, ENTITY_ID>
)

; A demand to delete an entity or list of entities.
MESSAGE_DELETE_ENTITY = (
    MESSAGE_DELETE_ENTITY_ID,
    ENTITY_ID
)

MESSAGE_DELETE_ENTITY_BATCH = (
    MESSAGE_DELETE_ENTITY_BATCH_ID,
    ARRAY<u32, ENTITY_ID>
)

; ==============================================================================
; Component modification
; Adds a component to an entity, given by entity_id
; If the entity id is missing, create entity first.
; If the component ID is negative, that means the component content should be
; ignored and the component removed from the entity

MESSAGE_COMPONENT = (
    MESSAGE_COMPONENT_ID,
    ENTITY_ID,
    ARRAY<u16, COMPONENT_MOD>
)

; Component modification. A component type id, followed by the component 
; content. If the ID is negative here, then the content does not exist, and 
; the component should be deleted on the entity.
COMPONENT_MOD = (
    COMPONENT_ID, ; if this is negative
    ? any ; this won't exist
)

; ==============================================================================
; Resource modification
MESSAGE_RESOUCE = (
    MESSAGE_RESOURCE_ID,
    ARRAY<u16, RESOURCE_MOD>
)

RESOURCE_MOD = (
    RESOURCE_ID, ; if this is negative
    ? any         ; this wont be here
)

; ==============================================================================
; Assets

MESSAGE_ASSET = (
    MESSAGE_ASSET_ID,
    ASSET_TYPE_ID,
    ASSET_ID,
    any,
)
