; Where do we obtain the bytes? 
; If an integer, it is a large asset, and should be obtained through the large
; asset system.
; If text, this must be a URL to fetch content from
; If bytes, the content is inline and immediate.
BUFFER_SOURCE = LARGE_ASSET_ID / text / bytes

; ==============================================================================
; Buffer asset

BUFFER_ASSET_ID = ASSET_ID

BUFFER_ASSET = {
    ; Optional name for asset
    ? 0: text,

    ; Content source
    1: BUFFER_SOURCE

    ; Buffer size hint. This should be the size of the byte buffer, but
    ; clients should not rely on this as truth. Useful for pre-allocation
    2: uint
}

; ==============================================================================
; Buffer view 

BUFFER_VIEW = {
    ; Buffer to draw bytes from
    0 : BUFFER_ASSET_ID,
    
    ; offset into the asset
    1 : uint

    ; length of the view
    2 : uint
}
