; Where do we obtain the bytes? 
; If an integer, it is a large asset, and should be obtained through the large
; asset system.
; If text, this must be a URL to fetch content from
; If bytes, the content is inline and immediate.
BUFFER_SOURCE = (
    (0, LARGE_ASSET_ID) / 
    (1, STRING) / 
    (2, BYTE_STRING)
)

; ==============================================================================
; Buffer asset

BUFFER_ASSET_ID = ASSET_ID

BUFFER_ASSET = (
    ; Optional name for asset
    OPTION<STRING>,

    ; Buffer size hint. This should be the size of the byte buffer, but
    ; clients should not rely on this as truth. Useful for pre-allocation
    u64,

    ; Content source
    BUFFER_SOURCE
)

; ==============================================================================
; Buffer view 

BUFFER_VIEW = (
    ; Buffer to draw bytes from
    BUFFER_ASSET_ID,
    
    ; offset into the asset
    u64,

    ; length of the view
    u64
)
