IMAGE_ASSET_ID = ASSET_ID

IMAGE_ASSET = {
    ; Optional name for asset
    ? 0: text,
    ; Data
    1: BUFFER_VIEW,
    ; Sampler
    ? 2 : SAMPLER_INFO,
    ; Semantic
    ? 3 : IMAGE_SEMANTIC
}

SAMPLER_INFO = {
    ; address_mode_u
    ? 1: ImageAddressMode                
    ; address_mode_v
    ? 2: ImageAddressMode                
    ; address_mode_w
    ? 3: ImageAddressMode                
    ; mag_filter
    ? 4: ImageFilterMode                 
    ; min_filter
    ? 5: ImageFilterMode                 
    ; mipmap_filter
    ? 6: ImageFilterMode                 
    ; lod_min_clamp
    ? 7: float32                         
    ; lod_max_clamp
    ? 8: float32                         
    ; compare (disabled for now)
    ; ? 9: ImageCompareFunction 
    ; anisotropy_clamp  
    ? 10: uint                         
    ; border_color (optional)
    ? 11: ImageSamplerBorderColor        
}

ImageAddressMode = 
    0 / ; Clamp to edge
    1 / ; Repeat
    2 / ; Mirrored repeat
    3   ; Clamp to border

ImageFilterMode = 
    0 / ; Nearest
    1   ; Linear

;ImageCompareFunction = uint  ; Enum: 0 = Never, 1 = Less, 2 = Equal, ?.
ImageSamplerBorderColor = 
    0 / ; TransparentBlack
    1 / ; OpaqueBlack
    2 / ; OpaqueWhite
    3   ; Zero

IMAGE_SEMANTIC = 
    0 / ; Color
    1   ; Data