; ==============================================================================
; Standard material asset
; Represents a classic Burley-type PBR shaders with common extensions

STD_MAT_ASSET_ID = ASSET_ID

STD_MAT_ASSET = (
    ; Bit flags
    MAT_FLAGS,

    ; Base color
    SRGBA_8,

    ; Perceptual roughness. 
    NORMALIZED_FLOAT,

    ; Metallic.
    NORMALIZED_FLOAT,

    ; Index of Refraction (IOR). Typical: [1.0, 2.5]
    float,

    ; Lightmap exposure multiplier. Default: 1.0
    float,

    ; Optional color texture
    color_map: EXTERNAL_OPTION<TEXTURE_REFERENCE>,

    ; Optional ORM texture mapping
    orm_map: EXTERNAL_OPTION<ORM_MAP>,

    ; Optional Normal mapping.
    normal_map: EXTERNAL_OPTION<TEXTURE_REFERENCE>,

    EXTERNAL_OPTION<THICKNESS>,

    EXTERNAL_OPTION<TRANSMISSION>,

    EXTERNAL_OPTION<CLEARCOAT>,

    EXTERNAL_OPTION<ANISOTROPY>,

    EXTERNAL_OPTION<PARALLAX>,

    ; Optional emissive control
    EXTERNAL_OPTION<EMISSION>,    

    ; UV1 transform matrix. Default: identity matrix
    EXTERNAL_OPTION<AFFINE2>,

    ; UV2 transform matrix. Default: identity matrix
    EXTERNAL_OPTION<AFFINE2>,

    EXTENSION_POINT
)

; Option flags for this material
; Bit 0: double_sided?
; Bit 1: unlit?
; Bit 2: fog DISabled?
; Bit 3, 4 : u2 -> FACE
; Bit 5, 6 : u2 -> ALPHA_MODE
; Bit 7: Color texture?
; Bit 8: ORM texture?
; Bit 9: Normal map?
; Bit 10: Thickness?
; Bit 11: Transmission?
; Bit 12: Clearcoat?
; Bit 13: Aniso?
; Bit 14: Parallax?
; Bit 15: Emission?
; Bit 16: UV1?
; Bit 17: UV2?
; 18 - 32 RESERVED
MAT_FLAGS = u32

TEXTURE_REFERENCE = (
    UV_CHANNEL, 
    IMAGE_ASSET_ID
)

; This is the common Occlusion, Roughness, Metallic map, stored as normalized RGB
ORM_MAP = (
    UV_CHANNEL, 
    IMAGE_ASSET_ID
)

EMISSION = (
    ; Emissive color. Default: [0.0, 0.0, 0.0, 1.0]
    LINEAR_RGBA,

    ; Emissive exposure weight. Range: [0.0, 1.0], Default: 1.0
    NORMALIZED_FLOAT,

    OPTION<TEXTURE_REFERENCE>,
)

TRANSMISSION = (
    ; Diffuse transmission. Range: [0.0, 1.0], Default: 0.0
    NORMALIZED_FLOAT,
    ; Specular transmission. Range: [0.0, 1.0], Default: 0.0
    NORMALIZED_FLOAT,

    ; Diffuse transmission texture. Default: none
    OPTION<TEXTURE_REFERENCE>,
    ; Specular transmission texture. Default: none
    OPTION<TEXTURE_REFERENCE>,
)

THICKNESS = (
    ; Thickness. Range: [0.0, inf), Default: 1.0
    float,

    ; Attenuation distance. Default: inf (no attenuation)
    float,

    ; Attenuation color. Default: [1.0, 1.0, 1.0, 1.0]
    SRGBA_8,

    ; Thickness texture. Default: none
    OPTION<TEXTURE_REFERENCE>,
)

CLEARCOAT = (
    ; Clearcoat. Range: [0.0, 1.0], Default: 0.0
    NORMALIZED_FLOAT,
    ; Clearcoat roughness. Range: [0.0, 1.0], Default: 0.0
    NORMALIZED_FLOAT,

    ; Clearcoat UV channel. Default: 0
    OPTION<UV_CHANNEL>,

    ; Clearcoat texture. Default: none
    OPTION<IMAGE_ASSET_ID>,

    ; Clearcoat roughness texture. Default: none
    OPTION<IMAGE_ASSET_ID>,

    ; Clearcoat normal texture. Default: none
    OPTION<IMAGE_ASSET_ID>,
)

PARALLAX = (
    ; Depth bias. Default: 0.0
    float,
    ; Parallax depth scale. Default: 0.05
    float,
    ; Max parallax layer count. Default: 32.0
    float,

    ; Parallax UV channel
    UV_CHANNEL,

    ; Depth map. Default: none
    IMAGE_ASSET_ID,

    ; Parallax mapping method. Default: 0 (Occlusion)
    PARALLAX_MAPPING_METHOD,
)

ANISOTROPY = (
    ; Anisotropy strength. Range: [0.0, 1.0], Default: 0.0
    NORMALIZED_FLOAT,

    ; Anisotropy rotation. Range: [0.0, 1.0], Default: 0.0
    NORMALIZED_FLOAT,

    ; Anisotropy texture. Default: none
    TEXTURE_REFERENCE
)

; ===== Sub-types =====
SRGBA_8 = (u8, u8, u8, u8) ; RR GG BB AA
LINEAR_RGBA = (float, float, float, float) ; linear RGBA, range [0.0, inf)

; This is a normalized integer format, using a divisor of 65535. This should provide similar if not more
; precision than what would be obtained in a texture.
NORMALIZED_FLOAT = u16 

; this is a u8
UV_CHANNEL = 0 / 1 ; default: 0

FACE = u2 ; 0 = Front, 1 = Back, 2 = None ; default: 0

ALPHA_MODE = u2 ; 0 = Opaque, 1 = Mask, 2 = Blend, 3 = Premultiplied ; default: 0

PARALLAX_MAPPING_METHOD = u8 ; 0 = Occlusion, 1 = Relief ; default: 0

AFFINE2 = {
    ; mat2x3, rotation, scaling
    float ; default 1
    float ; default 0
    float ; default 1
    float ; default 0

    ; translation, x, y
    float ; default 0
    float ; default 0
}
