; ==============================================================================
; Standard material asset
; Represents a classic Burley-type PBR shaders with common extensions

STD_MAT_ASSET_ID = ASSET_ID
MATERIAL_ASSET_ID = STD_MAT_ASSET_ID

STD_MAT_ASSET = (
    ; Optional name for asset
    OPTION<STRING>,

    ; Base color
    SRGBA_8,

    ; Optional color texture
    OPTION<TEXTURE_REFERENCE>,

    ; Optional emissive control
    OPTION<EMISSION>,

    ; Perceptual roughness. 
    NORMALIZED_FLOAT,

    ; Metallic.
    NORMALIZED_FLOAT,

    ; Optional ORM texture mapping
    OPTION<ORM_MAP>,

    OPTION<TRANSMISSION>,

    OPTION<THICKNESS>,

    ; Index of Refraction (IOR). Typical: [1.0, 2.5]
    float,

    ; Optional Normal mapping.
    OPTIONAL<TEXTURE_REFERENCE>,

    OPTION<CLEARCOAT>,

    OPTION<ANISOTROPY>

    ; Double-sided rendering. Default: false
    ? 47: bool,

    ; Cull mode. Default: 0 (Front)
    ? 48: FACE,

    ; Unlit material (disable lighting). Default: false
    ? 49: bool,

    ; Fog enabled. Default: true
    ? 50: bool,

    ; Alpha mode. Default: 0 (Opaque)
    ? 51: ALPHA_MODE,

    OPTION<PARALLAX>,

    ; Lightmap exposure multiplier. Default: 1.0
    ? 57: float,

    ; UV1 transform matrix. Default: identity matrix
    ? 60: AFFINE2

    ; UV2 transform matrix. Default: identity matrix
    ? 60: AFFINE2
)

TEXTURE_REFERENCE = (
    UV_CHANNEL, 
    IMAGE_ASSET_ID
)

; This is the common Occlusion, Roughness, Metallic map, stored as normalized RGB
ORM_MAP = (
    UV_CHANNEL, 
    IMAGE_ASSET_ID
)

EMISSION = (
    ; Emissive color. Default: [0.0, 0.0, 0.0, 1.0]
    ? 4: LINEAR_RGBA,

    ; Emissive exposure weight. Range: [0.0, 1.0], Default: 1.0
    ? 5: float,

    ; Emissive texture UV channel. Default: 0
    ? 6: UV_CHANNEL,

    ; Emissive texture. Default: none
    ? 7: IMAGE_ASSET_ID,
)

TRANSMISSION = (
    ; Diffuse transmission. Range: [0.0, 1.0], Default: 0.0
    ? 14: float,

    ; Diffuse transmission UV channel. Default: 0
    ? 15: UV_CHANNEL,

    ; Diffuse transmission texture. Default: none
    ? 16: IMAGE_ASSET_ID,

    ; Specular transmission. Range: [0.0, 1.0], Default: 0.0
    ? 17: float,

    ; Specular transmission UV channel. Default: 0
    ? 18: UV_CHANNEL,

    ; Specular transmission texture. Default: none
    ? 19: IMAGE_ASSET_ID,
)

THICKNESS = (
    ; Thickness. Range: [0.0, inf), Default: 1.0
    ? 20: float,

    ; Thickness UV channel. Default: 0
    ? 21: UV_CHANNEL,

    ; Thickness texture. Default: none
    ? 22: IMAGE_ASSET_ID,

    ; Attenuation distance. Default: inf (no attenuation)
    ? 24: float,

    ; Attenuation color. Default: [1.0, 1.0, 1.0, 1.0]
    ? 25: SRGBA_8,
)

CLEARCOAT = (
    ; Clearcoat. Range: [0.0, 1.0], Default: 0.0
    ? 35: float,

    ; Clearcoat UV channel. Default: 0
    ? 36: UV_CHANNEL,

    ; Clearcoat texture. Default: none
    ? 37: IMAGE_ASSET_ID,

    ; Clearcoat roughness. Range: [0.0, 1.0], Default: 0.0
    ? 38: float,

    ; Clearcoat roughness UV channel. Default: 0
    ? 39: UV_CHANNEL,

    ; Clearcoat roughness texture. Default: none
    ? 40: IMAGE_ASSET_ID,

    ; Clearcoat normal UV channel. Default: 0
    ? 41: UV_CHANNEL,

    ; Clearcoat normal texture. Default: none
    ? 42: IMAGE_ASSET_ID,
)

PARALLAX = (
    ; Depth bias. Default: 0.0
    ? 52: float,

    ; Depth map. Default: none
    ? 53: IMAGE_ASSET_ID,

    ; Parallax depth scale. Default: 0.05
    ? 54: float,

    ; Parallax mapping method. Default: 0 (Occlusion)
    ? 55: PARALLAX_MAPPING_METHOD,

    ; Max parallax layer count. Default: 32.0
    ? 56: float,
)

ANISOTROPY = (
    ; Anisotropy strength. Range: [0.0, 1.0], Default: 0.0
    ? 43: float,

    ; Anisotropy rotation. Range: [0.0, 1.0], Default: 0.0
    ? 44: float,

    ; Anisotropy UV channel. Default: 0
    ? 45: UV_CHANNEL,

    ; Anisotropy texture. Default: none
    ? 46: IMAGE_ASSET_ID,
)

; ===== Sub-types =====
SRGBA_8 = (u8, u8, u8, u8) ; RR GG BB AA
LINEAR_RGBA = (float, float, float, float) ; linear RGBA, range [0.0, inf)

; This is a normalized integer format, using a divisor of 65535. This should provide similar if not more
; precision than what would be obtained in a texture.
NORMALIZED_FLOAT = u16 

; this is a u8
UV_CHANNEL = 0 / 1 ; default: 0

FACE = u8 ; 0 = Front, 1 = Back, 2 = None ; default: 0

ALPHA_MODE = u8 ; 0 = Opaque, 1 = Mask, 2 = Blend, 3 = Premultiplied ; default: 0

PARALLAX_MAPPING_METHOD = u8 ; 0 = Occlusion, 1 = Relief ; default: 0

AFFINE2 = {
    ; mat2x3, rotation, scaling
    float ; default 1
    float ; default 0
    float ; default 1
    float ; default 0

    ; translation, x, y
    float ; default 0
    float ; default 0
}
