; All components should have a static and dynamic section. The static section can be used to improve parsing 
; performance by allowing the parser read the entire section. The dynamic section should be used for 
; optional elements of the asset, or elements that have no fixed size.
; A common idiom is to use the static section for a header, complete with a u32 for flags that might determine
; how the dynamic section is parsed.




; All component type ids are i16
; These are not unsigned to allow signalling deletion

NAME_COMPONENT_ID = 1

TRANSFORM_COMPONENT_ID = 5
PROPOSED_TRANSFORM_COMPONENT_ID = 6

INTERACTIVE_COMPONENT = 7
CAN_TRANSLATE_COMPONENT = 8
CAN_ROTATE_COMPONENT = 9
CAN_SCALE_COMPONENT = 10

ACTIVATE_COMPONENT = 15

VISIBLE_COMPONENT = 20

CHILD_OF_COMPONENT = 25

MESH_COMPONENT_ID = 50
MATERIAL_COMPONENT_ID = 51