; All component type ids are i16
; These are not unsigned to allow signalling deletion

NAME_COMPONENT_ID = 1

TRANSFORM_COMPONENT_ID = 5
PROPOSED_TRANSFORM_COMPONENT_ID = 6

INTERACTIVE_COMPONENT = 7
CAN_TRANSLATE_COMPONENT = 8
CAN_ROTATE_COMPONENT = 9
CAN_SCALE_COMPONENT = 10

ACTIVATE_COMPONENT = 15

VISIBLE_COMPONENT = 20

CHILD_OF_COMPONENT = 25

MESH_COMPONENT_ID = 50
MATERIAL_COMPONENT_ID = 51