; All component type ids are u16

NAME_COMPONENT_ID = 1

TRANSFORM_COMPONENT_ID = 5
PROPOSED_TRANSFORM_COMPONENT_ID = 6

INTERACTIVE_COMPONENT = 6
CAN_TRANSLATE_COMPONENT = 7
CAN_ROTATE_COMPONENT = 8
CAN_SCALE_COMPONENT = 9

ACTIVATE_COMPONENT = 15

VISIBLE_COMPONENT = 20

CHILD_OF_COMPONENT = 25

MESH_COMPONENT_ID = 50
MATERIAL_COMPONENT_ID = 51