; Assign a non-unique text label to an entity
; This can be used for debugging, or for providing a human-friendly name to 
; an important entity. For this purpose, it is recommended that inspection or 
; other UI does not show un-named entities by default. 
NAME_COMPONENT = (
	STRING
)