; The position of this entity, relative to it's parent, if one exists 
; (see CHILD_OF_COMPONENT). If there is no parent, then it is a world-relative
; transform.
;
; Most transforms are composed of affine components. For compactness, the 
; transform can be specified in multiple ways. The first is the Affine-wise 
; approach. Here, position, rotation, and scaling can be specified individually.
;
; The second is Matrix-wise. In this approach, a single field of a matrix is
; provided with a transformation matrix. For common cases, a standard affine
; matrix can be used; a 4x3 matrix (col major). Most clients
; Will attempt to de-construct any matrix into an affine representation.
;
; It is an error to use both!
;
TRANSFORM_COMPONENT = (
    ;Flags
    u8, 

	; Affine Wise ===================
	; Position. If missing, assume zero
	OPTION<VEC3>,
	; Rotation. If missing, assume the identity rotation
	OPTION<QUAT>,
	; Scale. If missing, assume one
	; A single float implies an isotropic scale
	SCALE,

	; Matrix Wise ===================
	OPTION<[12* float]>
)

SCALE = (
    (0) ; none
    (1, float) ; isotropic
    (2, VEC3) 
)

; This component is an ephemeral advisory component
; This means that the component is sent from client to server, with the
; server using it to consider updates to the system. The server does NOT send 
; this component back.
; In this case,
; The server is being informed that a client would like to move an entity.
; This is tied in with the interactivity components; clients should send this
; instead of an update to a transform component when human interaction is happening.
; an example is dragging a probe item.  In some cases, the server may
; want to do something on every proposed motion, but delay sending back a position
; update until it is really ready.
PROPOSED_TRANSFORM_COMPONENT = TRANSFORM_COMPONENT
