; The position of this entity, relative to it's parent, if one exists 
; (see CHILD_OF_COMPONENT). If there is no parent, then it is a world-relative
; transform.
;
; It is an error to use both!
;
TRANSFORM_COMPONENT = (
    ;Flags
    FLAGS, 

	; Based on the flags
	; Position. If missing, assume zero. compression is provisional at this time
	? VEC3 / COMPRESSED_VEC3,
	; Rotation. If missing, assume the identity rotation
	? QUAT / COMPRESSED_QUAT,
	; Scale. If missing, assume one
	; A single float implies an isotropic scale
	? float / VEC3,
)

; bit 0,1 = parse translation, position is compressed
; bit 2,3 = parse rotation, rotation is compressed
; bit 4,5 = SCALE discriminant
FLAGS = u8;

SCALE = (
    0 / ; none
    1 / ; isotropic float scale
    2 ; full vec3 scale
)

; This component is an ephemeral advisory component
; This means that the component is sent from client to server, with the
; server using it to consider updates to the system. The server does NOT send 
; this component back.
; In this case,
; The server is being informed that a client would like to move an entity.
; This is tied in with the interactivity components; clients should send this
; instead of an update to a transform component when human interaction is happening.
; an example is dragging a probe item.  In some cases, the server may
; want to do something on every proposed motion, but delay sending back a position
; update until it is really ready.
PROPOSED_TRANSFORM_COMPONENT = TRANSFORM_COMPONENT


