; All types parsed as c-style, IEEE, little-endian

ENTITY_ID = u32

; An identifier for a component type
; Note: This is a signed integer!
COMPONENT_ID = i16

; An identifier for a resource type
RESOURCE_ID = i16

; An identifier for a specific asset. Different asset types are considered different namespaces for these IDs
ASSET_ID = u32

; A specific asset type
ASSET_TYPE_ID = u16

; Content byte size
CONTENT_SIZE = u16

; A 3D vector
VEC3 = ( float, float, float )

; A rotation quaternion. The basis coefficients are encoded in xyz, with the scalar in w
; This MUST be a normalized unit quaternion!
QUAT = (
	float,
	float,
	float,
	float
)



UUID = u128

; All strings are UTF8 encoded.
SMALL_STRING = ( u8, [ * u8 ] )
LARGE_STRING = ( u32, [ * u8 ] )
STRING = LARGE_STRING

; Arrays are preceeded by an integer count, followed by `count` number of those items
ARRAY<I, T> = (I, [ * T ])

; Map
MAP<I, K, V> = (I, [ * (K , V) ] )

BYTE_STRING = ARRAY<u64, u8>

OPTION<T> = (
    (0u8) /
    (1u8, T)
)

; This is an option which its presence is defined by some external flag or value. THIS DISCRIMINANT MUST BE DOCUMENTED.
EXTERNAL_OPTION<T> = (
    ? T
)

; An optional where a negative value is a sentinel for None
; T _MUST_ be a signed integer or floating point
NON_NEGATIVE_OPTION<T> = (
    (T(-1)) / ; false
    (T) ; true
)

RESULT<U, V> = (
    (1u8, U) /
    (0u8, V)
)

ANY = (
    (0) / ; undefined/missing. For null, consider a 0i64
    (1, bool) /
    (2, i64) /
    (3, float64) / ; double in C
    (4, STRING) /
    (5, ARRAY<u32, ANY>) /
    (6, MAP<u32, ANY, ANY>) /
    (7, BYTE_STRING) /
    (8, VEC3) /
    (9, QUAT) /
    (10, UUID) /
    (11, COMPONENT_ID) ; Component Type ID
    (12, ASSET_TYPE_ID) ; Asset Type ID
    (13, ASSET_TYPE_ID, ASSET_ID) ; An Asset, Type ID, Instance ID,
    (14, RESOURCE_ID) ; Resource Type ID
    (15, ENTITY_ID) ; An Entity
)

ANY_ID = (u8) ;; Maps to the above ID

; Tags 0 - 0xfff are reserved

EXTENSION_POINT = (
    ARRAY<u8, EXTENSION>
)

EXTENSION = (
    ; Tag, used to describe the structure
    tag: u16,
    ; Structure content, to be interpreted by the tag
    payload: ARRAY<u16, u8>
)
